version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.15.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install 
      - save_cache: 
          key: npm-v4-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules 
  test:
    docker:
      - image: cimg/node:14.15.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout 
      - restore_cache: 
          key: npm-v4-dependencies-{{ checksum "yarn.lock" }}       
      - run: 
          name: Lint && format check && test ci 
          command: |
            yarn lint 
            yarn format:check
            yarn test
workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test:
          requires: 
            - build 

